version: '3.7'
services: 
  wwww:
    image: php:apache
    volumes: 
      - "./:/var/www/html"
    ports:
      - 8080:80
      - 443:443
  db:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=php_docker
      - MYSQL_PASSWORD=password
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - 3306:3306      
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8081:80
    environment:
      - PMA_PORT=3306
      - PMA_HOST=db